stages:
  - test
  - deploy

before_script:
  - whoami
  - pwd
  - docker --version
  - |
    if docker compose version >/dev/null 2>&1; then
      export DC="docker compose"
    else
      export DC="docker-compose"
    fi
  - $DC version

test_compose:
  stage: test
  script:
    - ls -la
    - test -f docker-compose.yml
    - $DC config
  only:
    - internal-deploy

deploy_test:
  stage: deploy
  script:
    - echo "DEPLOY TEST"
    - $DC down || true
    - $DC pull
    - $DC up -d
    - docker ps -a
  only:
    - internal-deploy
