CREATE DATABASE IF NOT EXISTS snipeit
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'snipeit'@'%' IDENTIFIED BY 'SNIPEIT_DB_PASSWORD';
GRANT ALL PRIVILEGES ON snipeit.* TO 'snipeit'@'%';
FLUSH PRIVILEGES;
